package com.osulsa.apkbuilder.engine;

public enum TemplateErrorCode {
  TEMPLATE_CONTRACT_MISSING,
  TEMPLATE_CONTRACT_INVALID,
  TEMPLATE_MISSING_INTERNAL,
  TEMPLATE_CHECKSUM_MISMATCH,
  TEMPLATE_CORRUPT,
  TEMPLATE_INCOMPATIBLE,
  IMPORT_NO_ENTRY_POINT,
  IMPORT_INVALID_ARCHIVE,
  PATCH_MANIFEST_FAILED,
  PATCH_RESOURCES_FAILED,
  PATCH_ASSETS_FAILED,
  CAPABILITY_CONFIG_FAILED,
  ALIGN_FAILED,
  SIGNING_FAILED,
  SIGNATURE_VERIFY_FAILED,
  OUTPUT_VERIFY_FAILED
}
